### ISSUE TITLE
Installation: missing files

### ISSUE THREAD

**Issue by marcelmah** [mancuniancol/repository.magnetic#1]
Today I tried to add some extra providers (because TorrentZ is down atm), but none worked.
I installed the TorrentZ provider earlier on my RPI3 and today I switched my Windows 10 Kodi install to Magnetic but nothing worked. I noticed that every install I do via the repository only installs the addon.xml file.

I 'fixed' it by manually downloading the scripts and placing the files in the right location.

PS. this happens on the RPI3 and on the Windows 10 install

**Comment by mancuniancol** [comment]
This weekend, I've been released several versions and I think that it was the problem.  The repo takes time to refresh all the information and sometimes the zip files take longer than the .xml files.
I think the repo will be ok tomorrow.  I'm still working in the project, though.  Then, it will be more updates this week.  Sorry for the inconvenient. 

I will close this issue.

**Comment by mancuniancol** [comment]
Btw, you can check in your browser directly the repo:
https://offshoregit.com/pulsarunofficial/magnetic_repo/

**Comment by marcelmah** [comment]
Still happens today... even when I update, it downloads it again and only the addon.xml remains behind removing the rest.

**Comment by mancuniancol** [comment]
Well, I do not the administrator of that repo. I will try to contact him though. Any case, please go to this forum. https://forums.tvaddons.ag/addon-releases/31572-pulsar-providers-unofficial-pulsar-repo.html.

**Comment by mancuniancol** [comment]
I've created this repo is a mirror. I am the admin https://github.com/mancuniancol/repository.magnetic.mirror/archive/v0.1.2.zip

**Comment by marcelmah** [comment]
I'm READING the conversation on tvaddons.ag. I notice I'm not the only one... will follow progress there.
