### ISSUE TITLE
Can't find items mentioned in the tutorial

### ISSUE THREAD

**Issue by Tasosgemah** [mancuniancol/repository.magnetic#2]
I'm following this read me to install magnetic:

https://github.com/mancuniancol/repository.magnetic/blob/master/README.md

The tutorial says to install these items from the magnetic repo:

script.quasar.magnetic
searcher.torrenter.magnetic
script.module.magnetic

But when i browse the repo there are no such items inside. The only item that exists that has a similar name is one called: Script-Torrenter Searcher: Magnetic. Which i assume is the second item in the list. But i can't find the other two.

**Comment by mancuniancol** [comment]
the script.quasar.magnetic  = Magnetic Quasar Connector
searcher.torrenter.magnetic = Torrenter Searcher: Magnetic
 and script.module.magnetic = Magnetic Torrent Manager
